# Generated by Django 4.1.7 on 2023-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
