# Generated by Django 4.1.7 on 2023-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_register',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Register Code'),
        ),
    ]
